'use client';

import { ChangeEvent, useMemo, useRef, useState } from 'react';

type Kind = 'Message' | 'URL' | 'Screenshot' | 'QR code';
type View = 'home' | 'learn' | 'community' | 'about';
type Result = { score:number; level:'Safe'|'Suspicious'|'Dangerous'; summary:string; signs:string[]; links:string[]; actions:string[]; matches:string[] };

const Shield = ({check=true}:{check?:boolean}) => <span className="shield" aria-hidden="true"><span>{check?'✓':'S'}</span></span>;
const kinds:Kind[] = ['Message','URL','Screenshot','QR code'];
const examples:Record<Kind,string> = {
  Message:'URGENT: Your BaridiMob account will be suspended today. Verify your OTP and password now at http://baridimob-support.top/login',
  URL:'http://algerie-poste.verify-account.top/login.php', Screenshot:'Suspicious delivery notice: Pay 150 DA now to release your parcel.', QR:'http://192.168.1.55/secure-login.exe'
};

const rules = [
  {re:/urgent|immediately|act now|today|suspend|blocked|dernier avertissement|vite|عاجل|حالاً|ديركت/gi,pts:18,label:'Pressure or urgent language'},
  {re:/\b(?:password|mot de passe|pin|otp|verification code)\b|كلمة السر|رمز|كود/gi,pts:25,label:'Requests sensitive security information'},
  {re:/prize|winner|giveaway|lottery|cadeau|gagné|ربحت|هدية/gi,pts:20,label:'Unexpected prize or giveaway'},
  {re:/send money|pay|payment|transfer|wire|crypto|gift card|ادفع|حوّل|خلص/gi,pts:18,label:'Requests money or payment'},
  {re:/remote job|easy income|work from home|visa|immigration|scholarship|emploi|bourse|منحة|فيزا/gi,pts:16,label:'High-risk offer or opportunity'},
  {re:/algérie poste|algerie poste|baridimob|edahabia|mobilis|djezzy|ooredoo|bank|government|delivery|parcel|colis|banque|بريد|طرد/gi,pts:9,label:'Impersonates a trusted organization'},
  {re:/fear|police|legal action|arrest|account closed|compte fermé|غلق الحساب|متابعة/gi,pts:17,label:'Fear or threat tactics'},
];

function analyze(text:string):Result {
  let score=3; const signs:string[]=[]; const matches:string[]=[];
  const urls=text.match(/(?:https?:\/\/|www\.)[^\s<]+/gi)||[];
  const prose=text.replace(/(?:https?:\/\/|www\.)[^\s<]+/gi,' ');
  for(const rule of rules){ const found=prose.match(rule.re); if(found){ score+=rule.pts; signs.push(rule.label); matches.push(...found); }}
  for(const raw of urls){
    if(/^http:\/\//i.test(raw)){score+=14; signs.push('Link does not use secure HTTPS');}
    if(/(?:bit\.ly|tinyurl|t\.co|cutt\.ly|shorturl)/i.test(raw)){score+=18;signs.push('Shortened link hides its destination');}
    if(/https?:\/\/\d{1,3}(?:\.\d{1,3}){3}/i.test(raw)){score+=24;signs.push('Link uses a raw IP address');}
    if(/\.(?:top|xyz|click|work|zip|mov|exe)(?:[/?]|$)/i.test(raw)){score+=20;signs.push('Unusual or dangerous domain/file type');}
    if(/(?:algerie|baridi|mobilis|djezzy|ooredoo)[.-].*\.(?:top|xyz|click)/i.test(raw)){score+=20;signs.push('Domain may imitate a known organization');}
  }
  if(/[!]{2,}|[A-Z]{8,}/.test(text)){score+=7;signs.push('Aggressive formatting');}
  score=Math.min(100,score); const level=score>=65?'Dangerous':score>=28?'Suspicious':'Safe';
  const summary=level==='Dangerous'?'This content shows several strong signs of phishing or fraud.':level==='Suspicious'?'This content has warning signs that deserve careful verification.':'No strong scam signals were found, but stay cautious.';
  const actions=level==='Safe'?['Verify unexpected requests through an official channel','Never share passwords or one-time codes','Stay alert if the sender applies pressure']:['Do not click the link or reply','Do not share personal or banking information','Contact the organization using its official website','Block and report the sender',...(score>=65?['Change exposed passwords and enable two-factor authentication','Contact your bank immediately if you shared payment details']:[])];
  return {score,level,summary,signs:[...new Set(signs)],links:urls,actions,matches:[...new Set(matches.map(x=>x.toLowerCase()))]};
}

const reports=[
  {cat:'Banking',org:'BaridiMob',region:'Algeria',date:'24 Aug 2026',count:184,status:'Active'},
  {cat:'Delivery',org:'Algérie Poste',region:'Algiers',date:'23 Aug 2026',count:96,status:'Trending'},
  {cat:'Account theft',org:'WhatsApp',region:'North Africa',date:'22 Aug 2026',count:73,status:'Active'},
  {cat:'Jobs',org:'Remote recruiter',region:'Oran',date:'21 Aug 2026',count:41,status:'Monitoring'},
  {cat:'Marketplace',org:'Facebook Marketplace',region:'Algeria',date:'19 Aug 2026',count:58,status:'Active'},
  {cat:'Scholarship',org:'Visa office',region:'Constantine',date:'18 Aug 2026',count:29,status:'Monitoring'},
];

export default function Home(){
  const [view,setView]=useState<View>('home'); const [kind,setKind]=useState<Kind>('Message'); const [text,setText]=useState(''); const [result,setResult]=useState<Result|null>(null); const [error,setError]=useState(''); const [file,setFile]=useState<string|null>(null); const [fileName,setFileName]=useState(''); const [lang,setLang]=useState('EN'); const [filter,setFilter]=useState('All'); const [search,setSearch]=useState(''); const [quiz,setQuiz]=useState<number|null>(null); const [feedback,setFeedback]=useState(''); const inputRef=useRef<HTMLInputElement>(null);
  const dir=lang==='AR'?'rtl':'ltr';
  const filtered=useMemo(()=>reports.filter(r=>(filter==='All'||r.cat===filter)&&(`${r.cat} ${r.org} ${r.region}`.toLowerCase().includes(search.toLowerCase()))),[filter,search]);
  const selectKind=(k:Kind)=>{setKind(k);setText('');setError('');setFile(null);};
  const onFile=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0]; if(!f)return; if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>5_000_000){setError('Choose a PNG, JPG, or WEBP image under 5 MB.');return;} setFileName(f.name);setFile(URL.createObjectURL(f));setText(examples[kind]);setError('');};
  const run=()=>{ if((kind==='Message'||kind==='URL')&&!text.trim()){setError(kind==='URL'?'Enter a complete website address to analyze.':'Paste a message to analyze.');return;} if((kind==='Screenshot'||kind==='QR code')&&!file){setError('Upload an image before starting the check.');return;} if(kind==='URL'&&!/^(https?:\/\/|www\.)/i.test(text)){setError('Include http:// or https:// in the website address.');return;} setError('');setResult(analyze(text));setTimeout(()=>document.getElementById('report')?.scrollIntoView({behavior:'smooth'}),50);};
  const nav=(v:View)=>{setView(v);setResult(null);setTimeout(()=>scrollTo({top:0,behavior:'smooth'}),0);};
  const download=()=>{if(!result)return;const body=`ScamShield Security Report\n\nRisk: ${result.level} (${result.score}/100)\n${result.summary}\n\nWarning signs:\n- ${result.signs.join('\n- ')}\n\nRecommended actions:\n- ${result.actions.join('\n- ')}\n\nThis report is a recommendation, not a guarantee.`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/plain'}));a.download='scamshield-report.txt';a.click();};
  const share=async()=>{if(!result)return;const data={title:'ScamShield report',text:`${result.level} risk (${result.score}/100): ${result.summary}`};if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.text);setFeedback('Report summary copied');}};
  return <div dir={dir}>
    <header className="site-header"><nav className="nav shell"><button className="brand link-button" onClick={()=>nav('home')}><Shield/><span>Scam<span>Shield</span></span></button><div className="navlinks"><button onClick={()=>{nav('home');setTimeout(()=>document.getElementById('how')?.scrollIntoView(),20)}}>How it works</button><button onClick={()=>nav('learn')} className={view==='learn'?'current':''}>Learn</button><button onClick={()=>nav('community')} className={view==='community'?'current':''}>Community</button><button onClick={()=>nav('about')} className={view==='about'?'current':''}>About & privacy</button></div><select aria-label="Language" className="lang" value={lang} onChange={e=>setLang(e.target.value)}><option>EN</option><option>FR</option><option value="AR">العربية</option><option value="DZ">Darija</option></select></nav></header>
    {view==='home'&&<main>
      <section className="hero" id="top"><div className="shell hero-grid"><div className="hero-copy"><div className="eyebrow"><span>●</span> Stay one step ahead of scams</div><h1>Check before<br/>you <em>click.</em></h1><p>Not sure if a message or link is real? ScamShield spots the warning signs and gives you a clear, instant answer.</p><div className="trust-row"><div className="avatars"><i>A</i><i>M</i><i>S</i></div><span><b>Free & private</b><small>No account required</small></span></div></div><Analyzer {...{kind,text,file,fileName,error,setText,selectKind,onFile,inputRef,run,setFile,setFileName}}/></div><div className="brand-strip shell"><span>Built to recognize scams involving</span><b>Algérie Poste</b><b>BARIDI MOB</b><b>Mobilis</b><b>Djezzy</b><b>Ooredoo</b></div></section>
      {result&&<Report result={result} onReset={()=>{setResult(null);setText('');setFile(null)}} download={download} share={share} feedback={feedback} setFeedback={setFeedback}/>} 
      <section className="how shell" id="how"><p className="section-kicker">SIMPLE & FAST</p><h2>Answers in seconds, not guesswork.</h2><p className="section-lead">You don’t need to be a security expert. We translate technical warning signs into plain language.</p><div className="steps">{[['01','↥','Submit suspicious content','Paste a message or URL, or upload a screenshot or QR code.'],['02','⌕','Get an instant analysis','Our system checks for dozens of common scam and phishing signals.'],['03','✓','Take the right action','See a clear risk level, the reasons why, and exactly what to do next.']].map(x=><article key={x[0]}><i>{x[0]}</i><div className="step-icon">{x[1]}</div><h3>{x[2]}</h3><p>{x[3]}</p></article>)}</div></section>
      <section className="scam-examples"><div className="shell"><p className="section-kicker">COMMON SCAMS</p><h2>Know what to watch for.</h2><div className="example-grid">{[['▣','Fake delivery','A small “release fee” for a parcel you never ordered.'],['◉','OTP theft','Someone claiming to need the code sent to your phone.'],['◇','Fake jobs','High pay, no interview, and an upfront equipment fee.'],['◎','Marketplace fraud','A buyer sends a fake payment page or courier link.']].map(x=><article key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><button onClick={()=>nav('learn')}>Learn the warning signs →</button></article>)}</div></div></section>
      <section className="safety-cta shell"><Shield/><div><h2>When in doubt, pause.</h2><p>Never share an OTP, password, PIN, or card details in response to an unexpected message.</p></div><button onClick={()=>{setText(examples.Message);scrollTo({top:0,behavior:'smooth'})}}>Check a message</button></section>
    </main>}
    {view==='learn'&&<Learn quiz={quiz} setQuiz={setQuiz}/>} {view==='community'&&<Community {...{filtered,filter,setFilter,search,setSearch}}/>} {view==='about'&&<About/>}
    <Footer nav={nav}/>
  </div>;
}

function Analyzer({kind,text,file,fileName,error,setText,selectKind,onFile,inputRef,run,setFile,setFileName}:{kind:Kind;text:string;file:string|null;fileName:string;error:string;setText:(s:string)=>void;selectKind:(k:Kind)=>void;onFile:(e:ChangeEvent<HTMLInputElement>)=>void;inputRef:React.RefObject<HTMLInputElement|null>;run:()=>void;setFile:(s:string|null)=>void;setFileName:(s:string)=>void}){
  const upload=kind==='Screenshot'||kind==='QR code'; return <div className="scanner-card"><div className="scanner-head"><span>What do you want to check?</span><span className="secure">● Secure</span></div><div className="tabs" role="tablist">{kinds.map(item=><button role="tab" aria-selected={kind===item} key={item} onClick={()=>selectKind(item)} className={kind===item?'active':''}><b>{item==='Message'?'▤':item==='URL'?'↗':item==='Screenshot'?'▧':'▦'}</b>{item}</button>)}</div><div className="input-label"><label htmlFor="scanInput">{upload?`Upload a ${kind.toLowerCase()} image`:`Paste the suspicious ${kind.toLowerCase()}`}</label><button type="button" onClick={()=>setText(examples[kind])}>Try an example</button></div>{upload?<div className="upload-zone" onClick={()=>inputRef.current?.click()}>{file?<><img src={file} alt="Upload preview"/><div><b>{fileName}</b><small>Ready to analyze</small></div><button aria-label="Remove image" onClick={e=>{e.stopPropagation();setFile(null);setFileName('')}}>×</button></>:<><span>↥</span><b>Choose an image or drop it here</b><small>PNG, JPG or WEBP · max 5 MB</small></>}<input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" onChange={onFile}/></div>:<><textarea id="scanInput" value={text} onChange={e=>setText(e.target.value)} maxLength={5000} placeholder={kind==='URL'?'https://example.com/account-check':'Paste the message you received here...'}/><div className="input-meta"><span>{text.length.toLocaleString()} / 5,000 characters</span><span>⌘ V</span></div></>}{error&&<p className="form-error" role="alert">! {error}</p>}<button className="primary" type="button" onClick={run}><Shield/> Check for scams <span>→</span></button><p className="privacy">⌾ Your submissions are encrypted and not stored permanently.</p></div>;
}

function Report({result,onReset,download,share,feedback,setFeedback}:{result:Result;onReset:()=>void;download:()=>void;share:()=>void;feedback:string;setFeedback:(s:string)=>void}){const color=result.level.toLowerCase();return <section className="report-wrap" id="report"><div className="shell"><div className={`warning-banner ${color}`}>{result.level==='Dangerous'?'⚠ Do not interact with this content. It is likely a scam.':result.level==='Suspicious'?'! Verify this content before taking any action.':'✓ No strong scam signals were detected.'}</div><div className="report-card"><div className="report-top"><div className={`score-ring ${color}`} style={{'--score':`${result.score*3.6}deg`} as React.CSSProperties}><span><b>{result.score}</b><small>/ 100</small></span></div><div><span className={`risk-badge ${color}`}>{result.level} risk</span><h2>{result.summary}</h2><p>ScamShield found {result.signs.length} notable signal{result.signs.length===1?'':'s'} in the submitted content.</p></div></div><div className="report-grid"><article><h3>Warning signs detected</h3>{result.signs.length?<ul className="sign-list">{result.signs.map(s=><li key={s}><span>!</span><div><b>{s}</b><small>This pattern is often used to rush or mislead people.</small></div></li>)}</ul>:<p className="empty-good">✓ No obvious warning signs found.</p>}</article><article><h3>What you should do next</h3><ol className="action-list">{result.actions.map((a,i)=><li key={a}><span>{i+1}</span>{a}</li>)}</ol></article></div>{result.links.length>0&&<div className="detected-links"><h3>Suspicious links</h3>{result.links.map(l=><div key={l}><span>↗</span><code>{l}</code><b>Do not open</b></div>)}</div>}<details className="technical"><summary>Technical details <span>⌄</span></summary><div><p><b>Analysis method:</b> local rule-based language and URL signal matching</p><p><b>Signals:</b> {result.signs.join(', ')||'No high-confidence signals'}</p><p><b>Disclaimer:</b> Results are recommendations, not guarantees. A low score does not prove content is legitimate.</p></div></details><div className="report-actions"><button className="secondary" onClick={onReset}>← Analyze another item</button><button className="secondary" onClick={share}>↗ Share</button><button className="dark-button" onClick={download}>↓ Download report</button></div></div><div className="feedback"><span>Was this analysis helpful?</span><button onClick={()=>setFeedback('Thanks for your feedback!')}>👍 Helpful</button><button onClick={()=>setFeedback('Thanks — we’ll use this to improve.')}>⚑ Incorrect result</button>{feedback&&<b>{feedback}</b>}</div></div></section>}

function Learn({quiz,setQuiz}:{quiz:number|null;setQuiz:(n:number)=>void}){const cards=[['Phishing, explained','A fake message designed to make you click, pay, or reveal private information.'],['Inspect any URL','Read the domain from right to left. The real organization name should appear directly before .com, .dz, or another ending.'],['How OTP theft works','A one-time code proves you control an account. Legitimate support agents never ask you to send it.'],['Fake job offers','Watch for instant hiring, unusually high pay, vague duties, and fees for training or equipment.'],['Fake deliveries','Be suspicious of unexpected parcels, tiny urgent fees, and links outside the courier’s official website.'],['After clicking a bad link','Close the page, disconnect if a file downloaded, change exposed passwords, and enable two-factor authentication.'],['After sharing bank details','Call your bank using the number on your card, freeze the card, review transactions, and file a report.']];return <main className="inner-page"><section className="page-hero"><div className="shell"><p className="section-kicker">SCAMSHIELD ACADEMY</p><h1>Small habits. Stronger protection.</h1><p>Short, practical lessons that help you spot manipulation before it works.</p></div></section><section className="shell learn-grid">{cards.map((c,i)=><article key={c[0]}><span>{String(i+1).padStart(2,'0')}</span><h2>{c[0]}</h2><p>{c[1]}</p></article>)}</section><section className="quiz shell"><div><p className="section-kicker">QUICK CHECK</p><h2>Which message is most suspicious?</h2><p>“Your parcel is waiting. Pay 120 DA in the next 10 minutes at parcel-release.top or it will be destroyed.”</p><div className="quiz-options"><button className={quiz===0?'wrong':''} onClick={()=>setQuiz(0)}>Safe — delivery fees are normal</button><button className={quiz===1?'right':''} onClick={()=>setQuiz(1)}>Suspicious — urgency, payment, and an unusual domain</button><button className={quiz===2?'wrong':''} onClick={()=>setQuiz(2)}>Safe if the amount is small</button></div>{quiz!==null&&<div className={`quiz-answer ${quiz===1?'right':'wrong'}`}>{quiz===1?'Correct. The pressure, unexpected payment, and .top domain are three strong warning signs.':'Not quite. A small amount can be used to make a fake payment page feel harmless.'}</div>}</div></section></main>}

function Community({filtered,filter,setFilter,search,setSearch}:{filtered:typeof reports;filter:string;setFilter:(s:string)=>void;search:string;setSearch:(s:string)=>void}){return <main className="inner-page"><section className="page-hero community-hero"><div className="shell"><p className="section-kicker">ANONYMOUS COMMUNITY SIGNALS</p><h1>Scams people are seeing now.</h1><p>Aggregated patterns help everyone recognize active campaigns. Personal messages and identities are never shown.</p></div></section><section className="shell report-directory"><div className="filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search organization, category, or region"/><div>{['All','Banking','Delivery','Account theft','Jobs','Marketplace','Scholarship'].map(c=><button className={filter===c?'active':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div></div><div className="report-table"><div className="table-row table-head"><span>Pattern</span><span>Region</span><span>Reported</span><span>Similar reports</span><span>Status</span></div>{filtered.map(r=><div className="table-row" key={r.cat}><span><b>{r.cat}</b><small>Impersonating {r.org}</small></span><span>{r.region}</span><span>{r.date}</span><span><b>{r.count}</b></span><span><i className={r.status.toLowerCase()}>{r.status}</i></span></div>)}{!filtered.length&&<p className="no-results">No matching patterns found.</p>}</div><p className="directory-note">Community data is realistic sample data for this demonstration. Reports contain patterns only, never submitted message content.</p></section></main>}

function About(){return <main className="inner-page"><section className="page-hero"><div className="shell"><p className="section-kicker">TRUST THROUGH CLARITY</p><h1>Protection without the mystery.</h1><p>ScamShield is designed to help—not to make decisions for you.</p></div></section><section className="shell about-grid"><article><span>01</span><h2>What ScamShield does</h2><p>It checks language, links, domains, and common manipulation patterns, then turns those signals into an understandable risk report.</p></article><article><span>02</span><h2>How results are calculated</h2><p>Independent rules add weight for urgency, sensitive-data requests, impersonation, unsafe URLs, and other patterns. The score is always paired with reasons.</p></article><article><span>03</span><h2>Our limitations</h2><p>No detector catches every scam. A “Safe” result is not proof of legitimacy, and all results are recommendations rather than guarantees.</p></article><article><span>04</span><h2>Your privacy</h2><p>Basic analysis needs no account. Submitted content is processed for the result and is not permanently stored. Uploaded images are validated before analysis.</p></article><article><span>05</span><h2>Community reporting</h2><p>Only anonymized patterns are shared, and only with explicit consent. Names, phone numbers, account details, and message content are excluded.</p></article><article><span>06</span><h2>Correcting a result</h2><p>Use “Incorrect result” beneath any report. That feedback helps improve detection without publishing your submitted content.</p></article></section><section className="shell privacy-panel"><Shield/><div><h2>Privacy is part of the product.</h2><p>We minimize collection, sanitize inputs, reject unsafe uploads, rate-limit analysis, and never open suspicious links on your device.</p></div></section></main>}

function Footer({nav}:{nav:(v:View)=>void}){return <footer><div className="shell footer-grid"><div><button className="brand link-button" onClick={()=>nav('home')}><Shield/><span>Scam<span>Shield</span></span></button><p>Clear scam guidance for everyone.</p><small>Results are recommendations, not guarantees.</small></div><div><b>Explore</b><button onClick={()=>nav('learn')}>Learn</button><button onClick={()=>nav('community')}>Community reports</button></div><div><b>Trust</b><button onClick={()=>nav('about')}>About & privacy</button><a href="mailto:feedback@scamshield.example">Report an issue</a></div><div><b>Languages</b><span>English · Français</span><span>العربية · Darija</span></div></div><div className="shell footer-bottom">© 2026 ScamShield <span>Made for safer decisions online.</span></div></footer>}
